# Day 6 : Lanternfish

## Part 1 : Puzzle Description

The sea floor is getting steeper. Maybe the sleigh keys got carried this way?

A massive school of glowing [lanternfish](https://en.wikipedia.org/wiki/Lanternfish) swims past. They must spawn quickly to reach such large numbers - maybe **exponentially** quickly? You should model their growth rate to be sure.

Although you know nothing about this specific species of lanternfish, you make some guesses about their attributes. Surely, each lanternfish creates a new lanternfish once every `7` days.

However, this process isn't necessarily synchronized between every lanternfish - one lanternfish might have 2 days left until it creates another lanternfish, while another might have 4. So, you can model each fish as a single number that represents **the number of days until it creates a new lanternfish**.

Furthermore, you reason, a **new** lanternfish would surely need slightly longer before it's capable of producing more lanternfish: two more days for its first cycle.

So, suppose you have a lanternfish with an internal timer value of `3`:

- After one day, its internal timer would become `2`.
- After another day, its internal timer would become `1`.
- After another day, its internal timer would become `0`.
- After another day, its internal timer would reset to `6`, and it would create a **new** lanternfish with an internal timer of `8`.
- After another day, the first lanternfish would have an internal timer of `5`, and the second lanternfish would have an internal timer of `7`.

A lanternfish that creates a new fish resets its timer to `6`, **not** `7` (because `0` is included as a valid timer value). The new lanternfish starts with an internal timer of `8` and does not start counting down until the next day.

Realizing what you're trying to do, the submarine automatically produces a list of the ages of several hundred nearby lanternfish (your puzzle input). For example, suppose you were given the following list:

`3,4,3,1,2`

This list means that the first fish has an internal timer of `3`, the second fish has an internal timer of `4`, and so on until the fifth fish, which has an internal timer of `2`. Simulating these fish over several days would proceed as follows:

```text
Initial state: 3,4,3,1,2
After  1 day:  2,3,2,0,1
After  2 days: 1,2,1,6,0,8
After  3 days: 0,1,0,5,6,7,8
After  4 days: 6,0,6,4,5,6,7,8,8
After  5 days: 5,6,5,3,4,5,6,7,7,8
After  6 days: 4,5,4,2,3,4,5,6,6,7
After  7 days: 3,4,3,1,2,3,4,5,5,6
After  8 days: 2,3,2,0,1,2,3,4,4,5
After  9 days: 1,2,1,6,0,1,2,3,3,4,8
After 10 days: 0,1,0,5,6,0,1,2,2,3,7,8
After 11 days: 6,0,6,4,5,6,0,1,1,2,6,7,8,8,8
After 12 days: 5,6,5,3,4,5,6,0,0,1,5,6,7,7,7,8,8
After 13 days: 4,5,4,2,3,4,5,6,6,0,4,5,6,6,6,7,7,8,8
After 14 days: 3,4,3,1,2,3,4,5,5,6,3,4,5,5,5,6,6,7,7,8
After 15 days: 2,3,2,0,1,2,3,4,4,5,2,3,4,4,4,5,5,6,6,7
After 16 days: 1,2,1,6,0,1,2,3,3,4,1,2,3,3,3,4,4,5,5,6,8
After 17 days: 0,1,0,5,6,0,1,2,2,3,0,1,2,2,2,3,3,4,4,5,7,8
After 18 days: 6,0,6,4,5,6,0,1,1,2,6,0,1,1,1,2,2,3,3,4,6,7,8,8,8,8
```

Each day, a `0` becomes a `6` and adds a new `8` to the end of the list, while each other number decreases by `1` if it was present at the start of the day.

In this example, after `18` days, there are a total of `26` fish. After `80` days, there would be a total of `5934`.

Find a way to simulate lanternfish. **How many lanternfish would there be after 80 days?**

## Load Lanternfish

In [1]:
import numpy as np
import time

def load_lanternfish(use_example: bool = False) -> np.array:
    filename = "example" if use_example else "input"

    with open(filename, "r") as file:
        lanternfish = np.array([int(i) for i in file.read().splitlines()[0].split(",")])

    return lanternfish

## Part 1 : Puzzle Solution

In [2]:
def sim_days(lanternfish: np.array, num_days: int = 80) -> np.array:
    """Simulates the passing of the given number of days.

    This function takes advantage of the numpy array to perform
    quick easy operations on this array of lanternfish timers.

    Args:
        lanternfish (np.array): The list of lanternfish to start simulation from.
        num_days (int): The number of days to simulate. Defaults to 80.

    Returns:
        np.array: The new list of lanternfish after num_days of simulation.
    """

    for day in range(0, num_days):

        # Decrement all current lanternfish timers.
        lanternfish = lanternfish - 1

        # Add any newborns.
        for fish in lanternfish[lanternfish == -1]:
            lanternfish = np.append(lanternfish, 8)

        # Reset fish who just spawned a newborn.
        lanternfish[lanternfish == -1] = 6

    return lanternfish


# Simulation of 18 days (on example).
lanternfish = load_lanternfish(use_example=True)
print(lanternfish)

start = time.time()
lanternfish = sim_days(lanternfish, 18)
end = time.time()
print(lanternfish)
print(f"Number of lanternfish: {len(lanternfish)}")
print(f"Execution Time: {end - start:.6f}")

print()

# Simulation of 80 days (on example).
lanternfish = load_lanternfish(use_example=True)
print(lanternfish)

start = time.time()
lanternfish = sim_days(lanternfish, 80)
end = time.time()
print(lanternfish)
print(f"Number of lanternfish: {len(lanternfish)}")
print(f"Execution Time: {end - start:.3f}")

print()

# Simulation of 80 days (on input).
lanternfish = load_lanternfish()
print(lanternfish)

start = time.time()
lanternfish = sim_days(lanternfish, 80)
end = time.time()
print(lanternfish)
print(f"Number of lanternfish: {len(lanternfish)}")
print(f"Execution Time: {end - start:.3f}")


[3 4 3 1 2]
[6 0 6 4 5 6 0 1 1 2 6 0 1 1 1 2 2 3 3 4 6 7 8 8 8 8]
Number of lanternfish: 26
Execution Time: 0.000000

[3 4 3 1 2]
[0 1 0 ... 8 8 8]
Number of lanternfish: 5934
Execution Time: 0.024

[5 1 2 1 5 3 1 1 1 1 1 2 5 4 1 1 1 1 2 1 2 1 1 1 1 1 2 1 5 1 1 1 3 1 1 1 3
 1 1 3 1 1 4 3 1 1 4 1 1 1 1 2 1 1 1 5 1 1 5 1 1 1 4 4 2 5 1 1 5 1 1 2 2 1
 2 1 1 5 3 1 2 1 1 3 1 4 3 3 1 1 3 1 5 1 1 3 1 1 4 4 1 1 1 5 1 1 1 4 4 1 3
 1 4 1 1 4 5 1 1 1 4 3 1 4 1 1 4 4 3 5 1 2 2 1 2 2 1 1 1 2 1 1 1 4 1 1 3 1
 1 2 1 4 1 1 1 1 1 1 1 1 2 2 1 1 5 5 1 1 1 5 1 1 1 1 5 1 3 2 1 1 5 2 3 1 2
 2 2 5 1 1 3 1 1 1 5 1 4 1 1 1 3 2 1 3 3 1 3 1 1 1 1 1 1 1 2 3 1 5 1 4 1 3
 5 1 1 1 2 2 1 1 1 1 5 4 1 1 3 1 2 4 2 1 1 3 5 1 1 1 3 1 1 1 5 1 1 1 1 1 3
 1 1 1 4 1 1 1 1 2 2 1 1 1 1 5 3 1 2 3 4 1 1 5 1 2 4 2 1 1 1 2 1 1 1 1 1 1
 1 4 1 5]
[2 5 6 ... 8 8 8]
Number of lanternfish: 383160
Execution Time: 44.918


## Part 2 : Puzzle Description

Suppose the lanternfish live forever and have unlimited food and space. Would they take over the entire ocean?

After `256` days in the example above, there would be a total of `26984457539` lanternfish!

**How many lanternfish would there be after 256 days?**


## Part 2 : Puzzle Solution

In [3]:
def sim_days_rollup(lanternfish: np.array, num_days: int = 80) -> int:
    """Simulates the passing of the given number of days.

    This function takes advantage of the fact that we don't really
    need to keep track of timers for every single fish, we just
    need to keep track of all fish at a given stage of their life.
    Then after each day advance the counts to the next stage.

    Args:
        lanternfish (np.array): The list of lanternfish to start simulation from.
        num_days (int): The number of days to simulate. Defaults to 80.

    Returns:
        int: The total count of all fish after the given number of simulated days.
    """

    # There are at most 9 stages of life with 2 stages being juvinile stages (starting a 0).
    # Create an array whose elements are the number of fish in the stage specified by its index.
    stage_counts = np.array([len(lanternfish[lanternfish == i]) for i in range(0, 9)], dtype=np.int64)

    for day in range(0, num_days):

        # Decrement all current lanternfish timers.
        # Numpy's roll method will move each count to the left in the array,
        # rolling anything that goes off the left side back to the right side.
        stage_counts = np.roll(stage_counts, -1)

        # Any fish in stage 9 (index 8) are not actually newborns but rather fish
        # that just reproduced. We need to reset them to stage 7 (index 6) by
        # adding them to the number of fish that just became adults; formerly
        # stage 8 (index 7).
        stage_counts[6] += stage_counts[8]

        # Note, we do not modify stage 9 (index 8). The count left there will
        # be the same as the number of new fish.

    # Return a full count of all fish at all stages.
    return np.sum(stage_counts)


# Simulation of 80 days (on example).
lanternfish = load_lanternfish(use_example=True)
print(lanternfish)

start = time.time()
count = sim_days_rollup(lanternfish, 80)
end = time.time()
print(f"Number of lanternfish: {count}")
print(f"Execution Time: {end - start:.3f}")

# Simulation of 256 days (on example).
lanternfish = load_lanternfish(use_example=True)
print(lanternfish)

start = time.time()
count = sim_days_rollup(lanternfish, 256)
end = time.time()
print(f"Number of lanternfish: {count}")
print(f"Execution Time: {end - start:.3f}")

# Simulation of 80 days (on input).
lanternfish = load_lanternfish()
print(lanternfish)

start = time.time()
count = sim_days_rollup(lanternfish, 80)
end = time.time()
print(f"Number of lanternfish: {count}")
print(f"Execution Time: {end - start:.3f}")

# Simulation of 256 days (on input).
lanternfish = load_lanternfish()
print(lanternfish)

start = time.time()
count = sim_days_rollup(lanternfish, 256)
end = time.time()
print(f"Number of lanternfish: {count}")
print(f"Execution Time: {end - start:.3f}")

[3 4 3 1 2]
Number of lanternfish: 5934
Execution Time: 0.001
[3 4 3 1 2]
Number of lanternfish: 26984457539
Execution Time: 0.004
[5 1 2 1 5 3 1 1 1 1 1 2 5 4 1 1 1 1 2 1 2 1 1 1 1 1 2 1 5 1 1 1 3 1 1 1 3
 1 1 3 1 1 4 3 1 1 4 1 1 1 1 2 1 1 1 5 1 1 5 1 1 1 4 4 2 5 1 1 5 1 1 2 2 1
 2 1 1 5 3 1 2 1 1 3 1 4 3 3 1 1 3 1 5 1 1 3 1 1 4 4 1 1 1 5 1 1 1 4 4 1 3
 1 4 1 1 4 5 1 1 1 4 3 1 4 1 1 4 4 3 5 1 2 2 1 2 2 1 1 1 2 1 1 1 4 1 1 3 1
 1 2 1 4 1 1 1 1 1 1 1 1 2 2 1 1 5 5 1 1 1 5 1 1 1 1 5 1 3 2 1 1 5 2 3 1 2
 2 2 5 1 1 3 1 1 1 5 1 4 1 1 1 3 2 1 3 3 1 3 1 1 1 1 1 1 1 2 3 1 5 1 4 1 3
 5 1 1 1 2 2 1 1 1 1 5 4 1 1 3 1 2 4 2 1 1 3 5 1 1 1 3 1 1 1 5 1 1 1 1 1 3
 1 1 1 4 1 1 1 1 2 2 1 1 1 1 5 3 1 2 3 4 1 1 5 1 2 4 2 1 1 1 2 1 1 1 1 1 1
 1 4 1 5]
Number of lanternfish: 383160
Execution Time: 0.002
[5 1 2 1 5 3 1 1 1 1 1 2 5 4 1 1 1 1 2 1 2 1 1 1 1 1 2 1 5 1 1 1 3 1 1 1 3
 1 1 3 1 1 4 3 1 1 4 1 1 1 1 2 1 1 1 5 1 1 5 1 1 1 4 4 2 5 1 1 5 1 1 2 2 1
 2 1 1 5 3 1 2 1 1 3 1 4 3 3 1 1 3 1 5 1 1 3 1 1 4 4 1 1 

## Notes

In the first part of the solution I used Numpy library which typically provides some convienient and efficient array operations. However, one of the methods it uses to make things efficient is always allocating the entire array in continguous memory. This means appending new elements to a Numpy array actually requires the entire array to be copied in memory to a new location big enough to accept this additional element. Of the three operations done on the Numpy array, two of them require this copying of the array process.

Despite the above mentioned inefficiencies, this solution still worked fairly well for the first part. The example input tests each completed in milliseconds or less, and the problem input took ~44 seconds to complete. However, when moving on to the second part of the problem, where 256 days needed to be simulated, it never completed. I let it run on the example input over night; over seven hours before cancelling it.

At first I thought about parallelizing the task by spining up a new process each the number of total fish hit a certain size. Split list of fish and run them separately in different processes. However, even if I managed to do this without spinning up too many processes, there would still be an issue with memory. Each of the methods above involve using a list whose elements are each fish's timer. If each fish's timer is an `int32`, then that means each fish requires 4-bytes of memory to store its timer. The example input alone will reach `~26` billion fish after `256` cycles, which will require `~100GB` of memory. My final solution for my problem input returned `~1.7` trillion fish after `256` cycles, which would have required `~6TB` of memory.

Obviously I needed a solution that doesn't actually keep track of each individual fish timer. Instead, I'll simply keep track of how many fish are in each of the 9 possible stages of a fish's reproduction cycle, two of which are juvinile stages. So in total I only need to keep track of 9 numbers at any given time. The first index of the list (i.e `0` index), would contain a count of all fish about to reproduce, second element (i.e. index `1`) would have the count of each fish with one day left, and so on. The last two stages, `8` (index `7`) and `9` (index `8`), are the juvinile stages.

After each day cycle, each of the counts in each of the 9 stages shift left in the array. Index `1` moves to index `0`, and index `0` moves to the back of the list at index `8` (stage `9`). Each of the fish that wrapped around to the end just reproduced. That number in the last index of the array will represent the new born fish. We then add that same number to the fish that just moved from stage `8` (index `7`) to stage `7` (index `6`). This stage `7` (index `6`) now has all the fish that just reproduced and all the fish that just became adults. The day's cycle is done and repeats on the next cycle. After all requested days have passed, we simply add up the counts for all stages.

This method was of course way faster, only ever working with an array of size `9`. I did run into an issue where `int32` was not a big enough data type to store the counts once we moved to the problem input. I had to specify the `int64` data type to get around this. While this worked, it means that there is still an upper bound to how many cycles can be simulated as eventually the counts would get even bigger than an `int64`. It might make sense to not use Numpy in this example and instead just use normal python lists and `int`'s, as python `int`'s are only bound by the amount of memory you have.

Note, it is also possible there is a purely mathematical way to solve this problem that would avoid the need to do any counting at all. Perhaps some kind of exponential formula or factorial.